### ISSUE TITLE
Listing view does not return to top of page after clicking new page.

### ISSUE THREAD

**Issue by jonlarson** [duosearch/Duo-Search#2] opened 2016-08-10 21:26 UTC
https://duosear.ch/listings

On the listings view, if I click to go to a new result page, the results will populate, but will remain scrolled to the bottom. This is very annoying since I have to manually scroll back up.

**Comment by JustinDrake** [comment] 2016-08-10 22:35
Thanks for the report Jon, and sorry you're having this issue.

I cannot reproduce this issue on Chrome, Safari or Firefox on Mac. From the listings page https://duosear.ch/listings, clicking on a listing brings me to the top of the page for that listing. (This is done with JavaScript by setting `scrollTop` to `0`.)

Can I ask which browser and OS you are using?

**Comment by jonlarson** [comment] 2016-08-11 00:20
On Ubuntu in both Chrome and Firefox. 

And to clarify, it's not clicking on a listing, but going to a new result page at the bottom of the listing results. e.g. going from page 1->2.

**Comment by duosearch** [comment] 2016-08-11 09:12
Ok, I now understand the issue. It should be fixed. Thanks for the report! 👍

**Closed as completed by duosearch** 2016-08-11 09:12 UTC
